version: '3.8'

services:
  security-assistant:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - security_data:/app/data
    environment:
      - EMBEDDING_MODEL=all-MiniLM-L6-v2
      - VECTOR_DB_TYPE=faiss
      # Uncomment and add appropriate credentials for LLM integration
      # - LLM_PROVIDER=azure_openai
      # - LLM_API_KEY=your-api-key
      # - LLM_ENDPOINT=your-endpoint
      # - LLM_DEPLOYMENT=your-deployment
      # - LLM_MODEL=gpt-4
    restart: unless-stopped

volumes:
  security_data:
    driver: local
